apiVersion: apps/v1
kind: Deployment
metadata:
  name: myappdeploy
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: nodecontain
        image: nikkoworld/jennode
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: myappservice
spec:
  selector:
    app: myapp
  type: LoadBalancer
  ports:
  - port: 3005
    targetPort: 3000
